Repository githubschool/darts, pull requests merged in 2021-08, with the labels that each got.

#12 Update 02-gusshawstewart.md
  _slides/02-gusshawstewart.md
Labels: documentation, enhancement, staging

#10 Update 08-goolja01.md
  _slides/08-goolja01.md
Labels: documentation, enhancement

#14 Update 09-lundpe01.md
  _slides/09-lundpe01.md
Labels: good first issue

#16 Update 03-ArtWeissLexisNexis.md
  _slides/03-ArtWeissLexisNexis.md
Labels: documentation
